### Testing 404 error route
GET http://localhost:3000/route/that/doesNotExists

### Testing protected route
GET http://localhost:3000/api/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTI4NDE4NDMsImV4cCI6MTYxMjg0MjQ0MywiYXVkIjoiQVN4VjNWVmlpQ1U4SDRMVVcyc0kiLCJpc3MiOiJodHRwczovL2luc2NyaXBjaW9uZXMtZWxlY2Npb25lcy11bmktMjAyMC5uZXRsaWZ5LmFwcCJ9.UBW-KQIfi-UvJ-9FdO_pPjzgqF864Rf0MFQuRhudzPw
Content-Type: application/json

{
  "args": {
    "id": "ASxV3VViiCU8H4LUW2sI"
  }
}

### Testing login route
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "args": {
    "id": "ASxV3VViiCU8H4LUW2sI"
  }
}

###Testing refresh token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "args": {
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDU2NTY0MjcsImV4cCI6MTYwNTc0MjgyNywiYXVkIjoiMSIsImlzcyI6Imh0dHBzOi8vaW5zY3JpcGNpb25lcy1lbGVjY2lvbmVzLXVuaS0yMDIwLm5ldGxpZnkuYXBwIn0.zDPQQ17cxnEKjD9Yro-t0mE0WCsVppvwJclBJ02tkWo"
  }
}

### Testing users/verify/:code
GET http://localhost:3000/api/user/verify/20140118I?documentType=1

### Testing users/notify
PATCH http://localhost:3000/api/user/notify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTI4MzkxMjMsImV4cCI6MTYxMjgzOTcyMywiYXVkIjoiQVN4VjNWVmlpQ1U4SDRMVVcyc0kiLCJpc3MiOiJodHRwczovL2luc2NyaXBjaW9uZXMtZWxlY2Npb25lcy11bmktMjAyMC5uZXRsaWZ5LmFwcCJ9.0zAm0uKDi9Q8CvnHCosXdCpQJ48it2g2PyYwtQLdgOo
Content-Type: application/json

{
  "args": {
    "id": "ASxV3VViiCU8H4LUW2sI",
    "gender": "M"
  }
}

### Testing list/createList
POST http://localhost:3000/api/list/createList?faculty=FC
Content-Type: application/json

{
  "args": {
    "owner": "PB1WbtisYdvcI2gnJwJF",
    "type": "dean"
  }
}

### Testing user/enrollList
POST http://localhost:3000/api/user/enroll/20140118I?documentType=1
Content-Type: application/json

{
  "args": {
    "id": "BohYVQsBpcPjH8MpqCKk",
    "owner": "1ZzkpBvPayaOLZzcvZQE"
  }
}

### Testing user/setCommitteeMembers
POST http://localhost:3000/api/user/setCommitteeMembers
Content-Type: application/json

{
  "args": [
    "20028502E",
    "19818216K",
    "19898357E",
    "19828141C",
    "20038822B",
    "20088664A",
    "20160374K",
    "20151315E",
    "20182163B"
  ]
}

### Testing /list/getListsOfUser
GET http://localhost:3000/api/list/getListsOfUser/ASxV3VViiCU8H4LUW2sI

### Testing /list/delete
DELETE http://localhost:3000/api/list/delete
Content-Type: application/json

{
  "args": {
    "owner": "Zpk5htPbalXNHVA589Sm",
    "id": "T7JDO7x7ExrrgKjANjW4"
  }
}

### Testing /list/finishRegistration/
PATCH http://localhost:3000/api/list/finishRegistration
Content-Type: application/json

{
  "args": {
    "id": "lNFXj4DHfJ6C4Zx4ZEm6",
    "owner": "004Kr7OTxVlquphiIQNG"
  }
}

### Testing /list/removeCandidate/:candaditeId
DELETE http://localhost:3000/api/list/removeCandidate/1ZzkpBvPayaOLZzcvZQE
Content-Type: application/json

{
  "args": {
    "owner": "1ZzkpBvPayaOLZzcvZQe",
    "id": "YwLmC8GszwWRLXo0AX70"
  }
}

### Tesing /list/filter/
GET http://localhost:3000/api/list/filter?faculty=FIIS&type=third-of-faculty

### Review /list/review
PATCH http://localhost:3000/api/list/review/TTxBOWGeIhLbAaEwxWjb/accepted
Content-Type: application/json

{
  "args": {
    "id": "6g1FTTlSKO0YsFkRWsFY",
    "observation": "Te aceptamos",
    "owner": "1ZzkpBvPayaOLZzcvZQE"
  }
}