### Testing 404 error route
GET http://localhost:3000/auth/refresh-token

### Testing protected route
GET http://localhost:3000/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWW91cnMgdHJ1bHkiLCJpYXQiOjE2MDU2NDI1MjYsImV4cCI6MTYwNTY0MzEyNiwiYXVkIjoiMSIsImlzcyI6Imh0dHBzOi8vaW5zY3JpcGNpb25lcy1lbGVjY2lvbmVzLXVuaS0yMDIwLm5ldGxpZnkuYXBwIn0.Tb8DZDW08tKvK3TBaOjyy58EFZpscSHQ_yoxKvuB2m0

### Testing auth route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "args": {
    "id": "1"
  }
}

### Testing login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "args": {
    "id": "1"
  }
}

### Testing users/verify/:code route
GET http://localhost:3000/api/user/verify/20140118I?documentType=2

### Testing users/notify
PATCH http://localhost:3000/api/user/notify
Content-Type: application/json

{
  "args": {
    "id": "DpLrOXMgtDnRkDAqU2U2"
  }
}

### Testing list/createList
POST http://localhost:3000/api/list/createList
Content-Type: application/json

{
  "args": {
    "owner": "pTA0tyvx3NjgGhic27k5",
    "type": "third-of-faculty"
  }
}

### Testing user/enrollList
POST http://localhost:3000/api/user/enroll/19968665E?documentType=1
Content-Type: application/json

{
  "args": {
    "id": "Ko2C6skVaA6Teog0dliY"
  }
}
