### Testing 404 error route
GET http://localhost:3000/route/that/doesNotExists

### Testing protected route
GET http://localhost:3000/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDU2NTY0NzcsImV4cCI6MTYwNTY1NzA3NywiYXVkIjoiMSIsImlzcyI6Imh0dHBzOi8vaW5zY3JpcGNpb25lcy1lbGVjY2lvbmVzLXVuaS0yMDIwLm5ldGxpZnkuYXBwIn0.6Zx2l4eqCc3_BjpU0fub9zebezhp_GhsQ3WtqucQ7Eo

### Testing auth route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "args": {
    "id": "1"
  }
}

### Testing login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "args": {
    "id": "1"
  }
}

###Testing refresh token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "args": {
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDU2NTY0MjcsImV4cCI6MTYwNTc0MjgyNywiYXVkIjoiMSIsImlzcyI6Imh0dHBzOi8vaW5zY3JpcGNpb25lcy1lbGVjY2lvbmVzLXVuaS0yMDIwLm5ldGxpZnkuYXBwIn0.zDPQQ17cxnEKjD9Yro-t0mE0WCsVppvwJclBJ02tkWo"
  }
}

### Testing users/verify/:code route
GET http://localhost:3000/api/user/verify/20172083F?documentType=1

### Testing users/notify
PATCH http://localhost:3000/api/user/notify
Content-Type: application/json

{
  "args": {
    "id": "DpLrOXMgtDnRkDAqU2U2"
  }
}

### Testing list/createList
POST http://localhost:3000/api/list/createList?faculty=FIIS
Content-Type: application/json

{
  "args": {
    "owner": "1ZzkpBvPayaOLZzcvZQE",
    "type": "dean"
  }
}

### Testing user/enrollList
POST http://localhost:3000/api/user/enroll/20140118I?documentType=1
Content-Type: application/json

{
  "args": {
    "id": "y1e1Bj1KvGACiBdW9vBd",
    "owner": "1ZzkpBvPayaOLZzcvZQE"
  }
}

### Testing /list/finishRegistration/
PATCH http://localhost:3000/api/list/finishRegistration
Content-Type: application/json

{
  "args": {
    "id": "lNFXj4DHfJ6C4Zx4ZEm6",
    "owner": "004Kr7OTxVlquphiIQNG"
  }
}

### Tesing /list/filter/
GET http://localhost:3000/api/list/filter?faculty=FIIS&type=third-of-faculty
